use nostr_pubsub_sim::SimulationReport;

pub const MACHINE_WOT_CSV_COLUMNS: &[&str] = &[
    "machine_positive_service_endorsements_published",
    "machine_positive_service_admissions",
    "machine_positive_endorsement_state_entries",
    "machine_rating_protocol_messages",
    "machine_rating_protocol_bytes",
    "machine_reputation_retained_ratings",
    "machine_reputation_retained_raters",
    "machine_reputation_trusted_roots",
    "adversarial_author_legitimate_reference_policy_drops",
    "admitted_rater_poison_published",
    "admitted_rater_poison_received",
    "admitted_rater_poison_ingested",
    "admitted_rater_poison_rejected",
    "admitted_rater_poison_removals",
    "admitted_rater_poison_service_admitted_rater",
    "admitted_rater_service_credits",
    "admitted_rater_service_bytes",
    "admitted_rater_poison_target_unknown_before",
    "admitted_rater_poison_target_received",
    "admitted_rater_poison_target_ingested",
    "admitted_rater_poison_target_removals",
    "admitted_rater_poison_target_recoveries",
    "admitted_rater_misbehavior_frames",
    "admitted_rater_revocations",
    "post_revocation_rating_published",
    "post_revocation_rating_target_policy_drops",
    "post_revocation_rating_target_received",
    "post_revocation_rating_target_ingested",
    "post_revocation_rating_influence",
    "unconnected_rating_pressure_published",
    "unconnected_rating_pressure_target_received",
    "unconnected_rating_pressure_target_ingested",
    "unconnected_rating_pressure_target_rejected",
    "unconnected_rating_pressure_distinct_raters",
    "unconnected_rating_pressure_retained_rating_delta",
    "unconnected_rating_pressure_retained_rater_delta",
    "unconnected_rating_pressure_rebuild_entry_delta",
    "unconnected_rating_pressure_anchor_positive_before",
    "unconnected_rating_pressure_anchor_stable_evaluations",
    "unconnected_rating_pressure_anchor_projection_changes",
];

pub fn machine_wot_values(report: &SimulationReport) -> Vec<String> {
    vec![
        report
            .machine_positive_service_endorsements_published
            .to_string(),
        report.machine_positive_service_admissions.to_string(),
        report
            .machine_positive_endorsement_state_entries
            .to_string(),
        report.machine_rating_protocol_messages.to_string(),
        report.machine_rating_protocol_bytes.to_string(),
        report.machine_reputation_retained_ratings.to_string(),
        report.machine_reputation_retained_raters.to_string(),
        report.machine_reputation_trusted_roots.to_string(),
        report
            .adversarial_author_legitimate_reference_policy_drops
            .to_string(),
        report.admitted_rater_poison_published.to_string(),
        report.admitted_rater_poison_received.to_string(),
        report.admitted_rater_poison_ingested.to_string(),
        report.admitted_rater_poison_rejected.to_string(),
        report.admitted_rater_poison_removals.to_string(),
        report
            .admitted_rater_poison_service_admitted_rater
            .to_string(),
        report.admitted_rater_service_credits.to_string(),
        report.admitted_rater_service_bytes.to_string(),
        report
            .admitted_rater_poison_target_unknown_before
            .to_string(),
        report.admitted_rater_poison_target_received.to_string(),
        report.admitted_rater_poison_target_ingested.to_string(),
        report.admitted_rater_poison_target_removals.to_string(),
        report.admitted_rater_poison_target_recoveries.to_string(),
        report.admitted_rater_misbehavior_frames.to_string(),
        report.admitted_rater_revocations.to_string(),
        report.post_revocation_rating_published.to_string(),
        report
            .post_revocation_rating_target_policy_drops
            .to_string(),
        report.post_revocation_rating_target_received.to_string(),
        report.post_revocation_rating_target_ingested.to_string(),
        report.post_revocation_rating_influence.to_string(),
        report.unconnected_rating_pressure_published.to_string(),
        report
            .unconnected_rating_pressure_target_received
            .to_string(),
        report
            .unconnected_rating_pressure_target_ingested
            .to_string(),
        report
            .unconnected_rating_pressure_target_rejected
            .to_string(),
        report
            .unconnected_rating_pressure_distinct_raters
            .to_string(),
        report
            .unconnected_rating_pressure_retained_rating_delta
            .to_string(),
        report
            .unconnected_rating_pressure_retained_rater_delta
            .to_string(),
        report
            .unconnected_rating_pressure_rebuild_entry_delta
            .to_string(),
        report
            .unconnected_rating_pressure_anchor_positive_before
            .to_string(),
        report
            .unconnected_rating_pressure_anchor_stable_evaluations
            .to_string(),
        report
            .unconnected_rating_pressure_anchor_projection_changes
            .to_string(),
    ]
}
